[package]
name = "pinocchio-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.94"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
pkg-config = "0.3.25"